#!/bin/bash

number="1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20"

Cell_file=Cell.out
Cell_dir=Cell_MQ
Structure_dir=structure_xyz_MQ
Structure_file=GaO_st.xyz
work_dir=Rings_MQ
sum_files=Cell.txt
mkdir -p "$work_dir/$Cell_dir"
mkdir -p "$work_dir/$Structure_dir"

for i in $number ; do
    Pathdir=/work/e05/e05/ucapcka/New_melting/Aug_MQ_2022/Sample_Tf3000k_CR1/CR_1_Ga2O3_st$i
    grep '127000' $Pathdir/GaO.out | tail -1 | awk '{print $5,$6,$7,$8,$14}'  > $Pathdir/$Cell_file
    grep '127000' $Pathdir/GaO.out | tail -1 | awk '{print $5,$6,$7,$8,$14}'  >> $sum_files
    tail -402 $Pathdir/GaO_model.xyz  > $Pathdir/GaO_st.xyz
    line=${i}
    #awk '{print $1,$2,$3}' $Cell_dir/$Cell_file > Cell_st$i.out
    cp $Pathdir/$Cell_file $work_dir/$Cell_dir/Cell_st${i}.xyz
    cp $Pathdir/$Structure_file $work_dir/$Structure_dir/GaO_st${i}.xyz
    #cp $option_files $work_dir
done
